version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies

### Backend

  - package-ecosystem: "uv"
    directory: "/service"
    schedule:
      interval: "daily"
    labels:
      - dependencies
      - backend

  - package-ecosystem: "docker"
    directory: "/service"
    schedule:
      interval: "daily"
    labels:
      - dependencies
      - frontend

### Frontend

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels:
      - dependencies
      - frontend

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - dependencies
