services:
  backend:
    build:
      context: service
      dockerfile: Dockerfile
    container_name: service
    ports:
      - "8022:8000"
    restart: unless-stopped
    environment:
      - MONGO_URI
      - MONGO_DATABASE
      - REDIS_URL
    depends_on:
      redis:
        condition: service_healthy


  worker:
    build:
      context: service
      dockerfile: Dockerfile
    container_name: service-worker
    restart: unless-stopped
    command: taskiq worker app.tkq:broker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app/src
    depends_on:
      redis:
        condition: service_healthy


  scheduler:
    build:
      context: service
      dockerfile: Dockerfile
    container_name: service-scheduler
    restart: unless-stopped
    command: taskiq scheduler app.broker:scheduler
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app/src
    depends_on:
      redis:
        condition: service_healthy


  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5