services:
  backend:
    image: ghcr.io/vatger/vatger-plugin:latest
    container_name: vatger-plugin-api
    ports:
      - "8022:8000"
    restart: unless-stopped
    environment:
      - MONGO_URI
      - MONGO_DATABASE
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  worker:
    image: ghcr.io/vatger/vatger-plugin:latest
    container_name: vatger-plugin-worker
    restart: unless-stopped
    command: taskiq worker app.taskiq_app:broker app.tasks
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  scheduler:
    image: ghcr.io/vatger/vatger-plugin:latest
    container_name: vatger-plugin-scheduler
    restart: unless-stopped
    command: taskiq scheduler app.broker:scheduler
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  redis:
    container_name: vatger-plugin-redis
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5