name: Plugin CI

on:
  push:
    branches: [main]
    paths:
      - 'plugin/**'
      - '.github/**'
  pull_request:
    paths:
      - 'plugin/**'
      - '.github/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check formatting
        uses: ./.github/actions/plugin/lint
        with:
          source-dir: plugin
